# Generated by Django 3.1.5 on 2021-07-22 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
