# Generated by Django 3.1.5 on 2021-07-28 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mesajmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesajmodel',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterField(
            model_name='mesajmodel',
            name='alan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlarim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesajmodel',
            name='gonderen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='mesajmodel',
            table='Mesajlar',
        ),
    ]
