# Generated by Django 3.1.5 on 2021-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210327_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilarmodel',
            name='detay_resim',
            field=models.ImageField(default='', upload_to='yazi_resimleri'),
        ),
    ]
