# Generated by Django 3.1.5 on 2021-04-07 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_yorummodel_cevaplar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorummodel',
            name='cevaplar',
        ),
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('duzenlenme_tarihi', models.DateTimeField(auto_now=True)),
                ('cevap', models.TextField()),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevap', to=settings.AUTH_USER_MODEL)),
                ('yorum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.yorummodel')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'db_table': 'cevap',
            },
        ),
    ]
