# Generated by Django 3.1.5 on 2021-07-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210408_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorummodel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='blog.yorummodel'),
        ),
        migrations.DeleteModel(
            name='Cevaplar',
        ),
    ]
