# Generated by Django 3.1.5 on 2021-07-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210719_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorummodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='blog.yorummodel'),
        ),
    ]
