# Generated by Django 3.1.5 on 2021-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210719_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilarmodel',
            name='bakis_sayi',
            field=models.IntegerField(default=0),
        ),
    ]
